import { View, Text, TouchableOpacity } from 'react-native'
import Feather from 'react-native-vector-icons/Feather';
import styles from "../CSS/CSSPolicyAndPrivacy";
import React from 'react'
import { ScrollView } from 'react-native-gesture-handler';

const ScreenPolicyAndPrivacy = ({ navigation }: any) => {
    return (
        <View>
            <View style={styles.container_header}>
                <TouchableOpacity onPress={() => navigation.goBack()}>
                    <Feather name="arrow-left" style={{ fontSize: 30 }} />
                </TouchableOpacity>
                <Text style={styles.text_title}>Chính sách và quyền riêng tư</Text>
            </View>
            <ScrollView>
                <View>
                    <Text style={{ fontSize: 20, color: '#000', textAlign: 'center' }}>CHÍNH SÁCH BẢO MẬT</Text>
                    <Text style={{ fontSize: 15, color: '#000' }}> Điều 1: Giới thiệu</Text>
                    <Text>
                        <Text>
                            1.1.       Chào mừng bạn đến với OderFood (bao gồm cả website hay ứng dụng di động OderFood) được vận hành bởi Công ty cổ phần OderFood và các công ty liên kết (gọi riêng và gọi chung là, OderFood, “chúng tôi”, hay “của chúng tôi”). OderFood nghiêm túc thực hiên trách nhiệm của mình theo pháp luật và các quy định hiện hành về bảo mật thông tin (“Luật riêng tư”) và cam kết tôn trọng quyền riêng tư và sự quan tâm của tất cả Người Sử Dụng đối với trang website và ứng dụng di động (“Nền tảng”) (chúng tôi gọi chung các nền tảng và dịch vụ chúng tôi cung cấp như được mô tả trong Nền tảng gọi chung là “Các Dịch vụ”). “Người sử dụng” là những cá nhân đăng ký một tài khoản với chúng tôi để sử dụng dịch vụ, bao gồm cả Người bán và Người mua (gọi riêng và gọi chung là, “Người sử dụng”, “bạn” hoặc “của bạn”). Chúng tôi nhận biết tầm quan trọng của dữ liệu cá nhân mà bạn đã tin tưởng giao cho chúng tôi và tin rằng chúng tôi có trách nhiệm quản lý, bảo vệ và xử lý dữ liệu cá nhân của bạn một cách thích hợp. Chính sách bảo mật này ("Chính sách bảo mật" hay "Chính sách") được thiết kế để giúp bạn hiểu được cách thức chúng tôi thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân mà bạn đã cung cấp cho chúng tôi và/hoặc lưu giữ về bạn, cho dù là hiện nay hoặc trong tương lai, cũng như để giúp bạn đưa ra quyết định sáng suốt trước khi cung cấp cho chúng tôi bất kỳ dữ liệu cá nhân nào của bạn.
                            1.2         "Dữ Liệu Cá Nhân" hay "dữ liệu cá nhân" có nghĩa là dữ liệu, dù đúng hay không, về một cá nhân mà thông qua đó có thể được xác định được danh tính, hoặc từ dữ liệu đó và thông tin khác mà một tổ chức có hoặc có khả năng tiếp cận. Các ví dụ thường gặp về dữ liệu cá nhân có thể gồm có tên, số chứng minh nhân dân và thông tin liên hệ.
                            1.3         Bằng việc sử dụng Các Dịch Vụ, đăng ký một tài khoản với chúng tôi, truy cập Nền tảng hay tiếp cận Các Dịch Vụ, bạn xác nhận và đồng ý rằng bạn chấp nhận các phương pháp, yêu cầu, và/hoặc chính sách được mô tả trong Chính sách bảo mật này, và theo đây bạn đồng ý cho phép chúng tôi thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân của bạn như mô tả trong đây. NẾU BẠN KHÔNG ĐỒNG Ý CHO PHÉP XỬ LÝ DỮ LIỆU CÁ NHÂN CỦA BẠN NHƯ MÔ TẢ TRONG CHÍNH SÁCH NÀY, VUI LÒNG KHÔNG SỬ DỤNG CÁC DỊCH VỤ CỦA CHÚNG TÔI HAY TRUY CẬP NỀN TẢNG HOẶC TRANG WEB CỦA CHÚNG TÔI. Nếu chúng tôi thay đổi Chính sách bảo mật của mình, chúng tôi sẽ thông báo cho bạn thông qua việc đăng tải những thay đổi đó hoặc Chính sách bảo mật sửa đổi trên Nền tảng của chúng tôi. Chúng tôi bảo lưu quyền chỉnh sửa Chính sách bảo mật này vào bất cứ thời điểm nào. Trong phạm vi tối đa cho phép theo luật hiện hành, việc bạn tiếp tục sử dụng Các Dịch vụ hoặc Nền tảng, bao gồm cả việc đặt bất kỳ đơn đặt hàng nào, sẽ đồng nghĩa với việc bạn chấp nhận với những thay đổi, chỉnh sửa được thực hiện đối với Chính sách bảo mật này.
                            1.4         Chính sách này được áp dụng đồng thời cùng với các thông báo, điều khoản hợp đồng, điều khoản chấp thuận khác liên quan đến việc chúng tôi thu thập, lưu trữ, sử dụng, tiết lộ và / hoặc xử lý dữ liệu cá nhân của bạn và sẽ không nhằm thay thế những thông báo hoặc điều khoản trước đó trừ khi chúng tôi tuyên bố thông tin khác.
                            1.5         Chính sách bảo mật này được áp dụng cho tất cả người sử dụng Các Dịch Vụ, bao gồm cả Người mua và Người bán trừ khi có thông tin tuyên bố khác.{'\n'}
                        </Text>
                        <Text style={{ fontSize: 15, color: '#000' }}> Điều 2: Khi nào OderFood thu thập dữ liệu cá nhân?{'\n'}</Text>
                        <Text>
                            2.1.         Chúng tôi sẽ/có thể thu thập dữ liệu cá nhân về bạn:
                            Khi bạn đăng ký và/hoặc sử dụng Các Dịch Vụ hoặc Nền tảng của chúng tôi, hoặc mở một tài khoản với chúng tôi;
                            Khi bạn gửi bất kỳ biểu mẫu nào, bao gồm, nhưng không giới hạn, đơn đăng ký hoặc các mẫu đơn khác liên quan đến bất kỳ sản phẩm và dịch vụ nào của chúng tôi, bằng hình thức trực tuyến hay dưới hình thức khác;
                            Khi bạn ký kết bất kỳ thỏa thuận nào hoặc cung cấp các tài liệu hoặc thông tin khác liên quan đến tương tác giữa bạn với chúng tôi, hoặc khi bạn sử dụng các sản phẩm và dịch vụ của chúng tôi;
                            Khi bạn tương tác với chúng tôi, chẳng hạn như thông qua các cuộc gọi điện thoại (có thể được ghi âm lại), thư từ, fax, gặp gỡ trực tiếp, các nền ứng dụng truyền thông xã hội và email; bao gồm cả khi bạn tương tác với các đại lý chăm sóc khách hàng của chúng tôi.
                            Khi bạn sử dụng các dịch vụ điện tử của chúng tôi, hoặc tương tác với chúng tôi qua ứng dụng hoặc sử dụng dịch vụ trên Nền tảng của chúng tôi. Trường hợp này bao gồm, nhưng không giới hạn, thông qua tập tin cookie mà chúng tôi có thể triển khai khi bạn tương tác với các Nền tảng hoặc Trang Web của chúng tôi;
                            Khi bạn cấp phép từ thiết bị của bạn để chia sẻ thông tin với ứng dụng hoặc Nền tảng của chúng tôi
                            Khi bạn liên kết tài khoản OderFood của bạn với tài khoản mạng xã hội hay tài khoản khác hoặc sử dụng các tính năng mạng xã hội khác, phù hợp với chính sách của nhà cung cấp;
                            Khi bạn thực hiện các giao dịch thông qua Dịch vụ của chúng tôi;
                            Khi bạn cung cấp ý kiến phản hồi hoặc gửi khiếu nại cho chúng tôi;
                            Khi bạn đăng ký tham gia một cuộc thi;
                            Khi bạn gửi dữ liệu cá nhân của bạn cho chúng tôi vì bất kỳ lý do gì.
                            Nội dung đề cập ở trên là không đầy đủ và chỉ đưa ra một số trường hợp phổ biến về thời điểm dữ liệu cá nhân về bạn có thể bị thu thập.{'\n'}
                        </Text>
                        <Text style={{ fontSize: 15, color: '#000' }}> Điều 3: OderFood sẽ thu thập những dữ liệu gì?{'\n'}</Text>
                        <Text>
                            3.1. Dữ liệu cá nhân mà Foody có thể thu thập bao gồm:
                            Họ tên
                            Địa chỉ email
                            Ngày sinh
                            Địa chỉ thanh toán và/hoặc giao nhận hàng
                            Tài khoản ngân hàng và thông tin thanh toán
                            Số điện thoại
                            Giới tính
                            Thông tin được gửi bởi hoặc liên quan đến (các) thiết bị được sử dụng để truy cập vào Các Dịch vụ hoặc Nền tảng của chúng tôi.
                            Hình ảnh, dữ liệu âm thanh hoặc các video mà bạn chia sẻ với chúng tôi;
                            Giấy tờ tùy thân do chính phủ cấp hoặc thông tin khác cần thiết cho sự thẩm định của chúng tôi, nhận biết khách hàng của bạn, xác minh danh tính hoặc các mục đích phòng chống gian lận;
                            Dữ liệu tiếp thị và truyền thông, chẳng hạn như sở thích của bạn khi nhận thông tin tiếp thị từ chúng tôi và các bên thứ ba, sở thích giao tiếp và lịch sử liên lạc của bạn với chúng tôi, các nhà cung cấp dịch vụ của chúng tôi và các bên thứ ba khác;
                            Dữ liệu sử dụng và dữ liệu giao dịch, bao gồm thông tin chi tiết về các tìm kiếm, đơn đặt hàng của bạn, quảng cáo và nội dung bạn tương tác trên Nền tảng cũng như các sản phẩm và dịch vụ khác liên quan đến bạn;
                            Dữ liệu về định vị
                            Bất kỳ thông tin nào khác về người dùng khi người dùng đăng nhập để sử dụng Các Dịch Vụ hoặc Nền tảng của chúng tôi, và khi người dùng sử dụng Các Dịch Vụ hoặc Nền tảng, cũng như thông tin về việc người dùng sử dụng Các Dịch Vụ hoặc Nền tảng của chúng tôi như thế nào; và
                            Dữ liệu tổng hợp về nội dung người dùng sử dụng.
                            3.2         Bạn đồng ý không cung cấp cho chúng tôi bất cứ thông tin nào không chính xác hoặc gây hiểu nhầm và bạn đồng ý sẽ thông báo cho chúng tôi về bất cứ thông tin nào không chính xác hoặc khi có sự thay đổi thông tin. Chúng tôi bảo lưu quyền tự quyết định khi yêu cầu các tài liệu cần thiết khác để xác minh thông tin được bạn cung cấp.
                            3.3.         Nếu bạn đăng nhập để trở thành Người sử dụng các Nền tảng của chúng tôi, sử dụng tài khoản mạng xã hội của Bạn (“Tài khoản Mạng Xã hội”), liên kết tài khoản ShopeeFood của bạn với Tài khoản Mạng Xã hội của bạn hoặc sử dụng bất cứ tính năng mạng xã hội ShopeeFood nào, chúng tôi có quyền truy cập thông tin mà bạn đã cung cấp một cách tự nguyên cho nhà cung cấp dịch vụ Tài khoản Mạng Xã hội của bạn tuân theo các chính sách của các nhà cung cấp dịch vụ này, và chúng tôi sẽ quản lý và sử dụng các dữ liệu cá nhân này của bạn theo các quy định của Chính sách này tại mọi thời điểm.
                            3.4.         Nếu bạn không muốn chúng tôi thu thập thông tin/dữ liệu cá nhân nói trên, bạn có thể chọn không tham gia vào bất kỳ lúc nào bằng cách thông báo bằng văn bản đến Nhân Viên Bảo Vệ Dữ Liệu của chúng tôi. Bạn có thể tìm thấy thêm thông tin về nội dung này trong mục "Bạn có thể rút lại sự cho phép xóa tên, yêu cầu truy cập hoặc điều chỉnh thông tin bạn đã cung cấp cho chúng tôi bằng cách nào?" dưới đây. Tuy nhiên, lưu ý rằng việc từ chối hoặc hủy bỏ cho phép chúng tôi thu thập, sử dụng hoặc xử lý dữ liệu cá nhân của bạn có thể ảnh hưởng đến việc bạn sử dụng Các Dịch Vụ và Nền tảng. Ví dụ như dịch vụ định vị sẽ không hoạt động nếu bạn không cho phép ứng dụng truy cập vị trí của bạn.{'\n'}</Text>

                        <Text style={{ fontSize: 15, color: '#000' }}>Điều 4: Thu thập các dữ liệu khác{'\n'}</Text>
                        <Text>
                            4.1.         Như với hầu hết các trang web và các ứng dụng di động khác, thông tin được gửi từ thiết bị của bạn có thể chứa dữ liệu về bạn, được một máy chủ web ghi lại khi bạn sử dụng Nền tảng của chúng tôi. Thông tin này bao gồm địa chỉ IP, hệ điều hành của máy tính/thiết bị di động, loại trình duyệt, loại thiết bị di động, các đặc điểm của thiết bị di động, mã định danh thiết bị thống nhất (UDID) hoặc mã định danh thiết bị di động (MEID) của thiết bị di động của bạn, địa chỉ tham chiếu của Trang Web (nếu có), các trang mà bạn đã truy cập đến trên trang web hoặc ứng dụng di động của chúng tôi và thời gian truy cập và đôi khi là "cookie" (có thể vô hiệu hóa bằng cách sử dụng tùy chọn trình duyệt của bạn) để giúp trang web ghi nhớ lần truy cập cuối cùng của bạn. Nếu bạn đăng nhập, thông tin này được liên kết với tài khoản cá nhân của bạn. Thông tin này cũng được đưa vào các số liệu thống kê ẩn danh để giúp chúng tôi hiểu được khách truy cập sử dụng Trang Web của chúng tôi như thế nào.
                            4.2.         Các ứng dụng di động của chúng tôi có thể thu thập thông tin chính xác về địa chỉ của thiết bị di động của bạn sử dụng các công nghệ như GPS, Wi-Fi,…. Chúng tôi thu thập, sử dụng, công bố và/hoặc xử lý các thông tin này cho một hoặc nhiều mục đích bao gồm các dịch vụ được cung cấp dựa trên vị trí mà bạn yêu cầu hoặc chuyển các nội dung có liên quan đến bạn dựa trên vị trí của bạn hoặc cho phép bạn chia sẻ vị trí của bạn cho các Người sử dụng khác như là một phần của các Dịch vụ được cung cấp bởi các ứng dụng di động của chúng tôi. Đối với phần lớn các thiết bị di động, bạn có thể rút lại sự cho phép để chúng tôi được thu thập các thông tin này dựa trên vị trí của bạn thông qua các cài đặt trên thiết bị. Nếu bạn có câu hỏi nào về cách thức vô hiệu hóa các dịch vụ vị trí trên thiết bị di động của bạn, vui lòng liên hệ với các nhà cung cấp dịch vụ thiết bị di động hoặc nhà sản xuất thiết bị của bạn.
                            4.3         Do khi bạn xem các trang trên trang web hoặc ứng dụng di động của chúng tôi, khi bạn xem các nội dung và quảng cáo và truy cập vào các phần mềm khác trên Nền tảng của chúng tôi hoặc thông qua Dịch vụ, phần lớn các thông tin giống nhau sẽ được gửi đến cho chúng tôi (bao gồm địa chỉ IP, hệ điều hành, v.v…); nhưng, thay vì các lượt xem trang, thiết bị của bạn gửi đến chúng tôi thông tin về các nội dung, quảng cáo được xem và/hoặc phần mềm được cài đặt trên các Dịch vụ và Nền tảng và thời gian.{'\n'}</Text>

                        <Text style={{ fontSize: 15, color: '#000' }}>Điều 5: Chúng tôi sử dụng thông tin bạn cung cấp cho chúng tôi như thế nào?{'\n'}</Text>
                        <Text>
                            5.1         Chúng tôi có thể thu thập, sử dụng, tiết lộ và/hoặc xử lý dữ liệu cá nhân của bạn cho các mục đích sau đây:
                            Để xem xét và/hoặc xử lý đơn đăng ký/giao dịch của bạn với chúng tôi hoặc giao dịch hay thư từ của bạn với các bên thứ ba qua Các Dịch Vụ;
                            Để quản lý, điều hành, cung cấp và/hoặc quản lý việc bạn sử dụng và/hoặc truy cập Các Dịch Vụ và các Nền tảng của chúng tôi (bao gồm các sở thích của bạn), cũng như quan hệ và tài khoản người dùng của bạn với chúng tôi;
                            Để đáp ứng, xử lý, giải quyết hoặc hoàn tất một giao dịch và/hoặc đáp ứng các yêu cầu của bạn đối với các sản phẩm và dịch vụ nhất định và thông báo cho bạn về các vấn đề dịch vụ và các hoạt động tài khoản bất thường;
                            Để thực thi các Điều Khoản Dịch Vụ của chúng tôi hoặc bất kỳ thỏa thuận giấy phép người dùng cuối nào áp dụng;
                            Để bảo vệ sự an toàn cá nhân và các quyền, tài sản hoặc sự an toàn của người khác;
                            Để nhận dạng, xác minh; đánh giá pháp lý, hoặc để hiểu mục đích của khách hàng của bạn;
                            Để duy trì và quản lý bất kỳ bản cập nhật phần mềm nào và/hoặc các bản cập nhật khác và sự hỗ trợ có thể được yêu cầu tùy lúc nhằm đảm bảo Các Dịch Vụ của chúng tôi hoạt động suôn sẻ;
                            Để giải quyết hoặc tạo điều kiện cho dịch vụ khách hàng, thực hiện các yêu cầu của bạn, giải quyết hoặc trả lời bất kỳ thắc mắc nào được gửi bởi (hoặc nhằm được gửi bởi) bạn hoặc thay mặt bạn;
                            Để liên hệ với bạn hoặc liên lạc với bạn qua điện thoại, tin nhắn văn bản và/hoặc tin nhắn fax, email và/hoặc thư hoặc cách khác nhằm mục đích quản trị và/hoặc quản lý quan hệ của bạn với chúng tôi hoặc việc bạn sử dụng Các Dịch Vụ của chúng tôi, chẳng hạn như ở việc truyền đạt thông tin hành chính cho bạn liên quan đến Các Dịch Vụ của chúng tôi. Bạn xác nhận và đồng ý rằng việc liên lạc này có thể được thực hiện bằng cách gửi thư qua đường bưu điện, tài liệu hoặc thông báo cho bạn, có thể dẫn đến việc tiết lộ dữ liệu cá nhân nhất định về bạn để cung cấp các tài liệu đó cũng như trên bao bì/phong bì;
                            Để cho phép Các người dùng khác tương tác, kết nối với bạn hoặc nhìn được một vài hoạt động của bạn trên Nền tảng, bao gồm để thông báo cho bạn khi một người dùng khác gửi cho bạn một tin nhắn riêng, đăng nhận xét cho bạn trên Nền tảng; hoặc được kết nối với bạn thông qua việc sử dụng các tính năng mạng xã hội trên Nền tảng;
                            Để tiến hành các hoạt động nghiên cứu, phân tích và phát triển (bao gồm phân tích dữ liệu, khảo sát, phát triển và/hoặc lập đặc tính sản phẩm và dịch vụ), để phân tích cách thức bạn sử dụng Các Dịch Vụ của chúng tôi, để gợi ý các sản phẩm và/ hoặc Các Dịch Vụ phù hợp với sở thích của bạn, để cải thiện Các Dịch Vụ hoặc sản phẩm của chúng tôi và/hoặc để nâng cao trải nghiệm khách hàng của bạn;
                            Để tạo điều kiện cho kiểm toán và khảo sát, ngoài những hoạt động khác, xác thực quy mô và thành phần của đối tượng mục tiêu, và hiểu được trải nghiệm của họ với Các Dịch Vụ của Foody;
                            Cho mục đích tiếp thị và quảng cáo, và trong trường hợp này, để gửi cho bạn qua các phương tiện và phương thức tiếp thị và các thông tin quảng bá và tài liệu liên quan đến các sản phẩm và/hoặc dịch vụ (bao gồm các sản phẩm và/hoặc dịch vụ của các bên thứ ba mà Foody có thể hợp tác hoặc liên kết) mà Foody (và/hoặc các công ty liên kết hoặc các tập đoàn có liên quan) có thể bán, tiếp thị hoặc quảng bá, cho dù các sản phẩm hoặc dịch vụ đó tồn tại vào lúc này hoặc sẽ được tạo ra trong tương lai. Bạn có thể hủy đăng ký nhận các thông tin tiếp thị tại bất cứ thời điểm nào bằng cách sử dụng chức năng hủy đăng ký trong các tài liệu tiếp thị điện tử. Chúng tôi có thể sử dụng các thông tin liên hệ của bạn để gửi các bản tin từ hoặc các tài liệu tiếp thị từ chúng tôi hoặc từ các công ty có liên quan;
                            Theo quy định của pháp luật hiện hành, và các yêu cầu của cơ quan nhà nước có thẩm quyền; hoặc trong trường hợp chúng tôi tin rằng việc tiết lộ thông tin này là cần thiết, bao gồm, nhưng không giới hạn, đáp ứng các quy định để tiết lộ thông tin theo yêu cầu của bất kỳ điều luật nào áp dụng với Foody hoặc với các tập đoàn và công ty có liên quan khác; (bao gồm, nếu có, việc hiển thị tên, thông tin liên hệ và thông tin công ty của bạn);
                            Để lập số liệu thống kê và nghiên cứu đáp ứng yêu cầu báo cáo và/hoặc duy trì sổ sách nội bộ hoặc theo quy chế;
                            Để thực hiện quy trình tìm hiểu và xác minh hoặc các hoạt động sàng lọc khác (bao gồm, nhưng không giới hạn, việc xác minh lý lịch) tuân thủ các nghĩa vụ theo quy định pháp luật hoặc các thủ tục kiểm soát rủi ro của chúng tôi, có thể được pháp luật yêu cầu hoặc có thể đã được chúng tôi áp dụng;
                            Để kiểm toán Các Dịch Vụ của chúng tôi hoặc hoạt động kinh doanh của Foody;
                            Để ngăn chặn hoặc điều tra bất kỳ hoạt động gian lận, phi pháp, thiếu sót hay hành vi sai trái nào, cho dù đã diễn ra hay chưa, có liên quan đến việc bạn sử dụng Các Dịch Vụ của chúng tôi hay không hay bất kỳ vấn đề nào phát sinh từ quan hệ của bạn với chúng tôi;
                            Để phản hồi bất kỳ khiếu nại thực tế hay đe dọa nào đưa ra chống lại Foody hoặc các khiếu nại khác mà nội dụng của chúng xâm phạm đến quyền của các bên thứ ba;
                            Để lưu trữ, lập máy chủ, sao lưu (cho dù là vì mục đích khôi phục sau thảm họa hoặc mục đích khác) đối với dữ liệu cá nhân của bạn;
                            Để xử lý và/hoặc tạo điều kiện cho một giao dịch tài sản kinh doanh hoặc một giao dịch tài sản kinh doanh tiềm năng, trường hợp giao dịch đó liên quan đến Foody như một bên tham gia hoặc chỉ liên quan đến một công ty hay công ty liên kết của Foody như một bên tham gia hoặc liên quan đến Foody và/hoặc bất kỳ một hay nhiều công ty hoặc công ty liên kết của Foody như (các) bên tham gia, và có thể có các tổ chức bên thứ ba khác tham gia giao dịch như thế. "Giao dịch tài sản kinh doanh" là các giao dịch mua, bán, cho thuê, sáp nhập, hợp nhất hoặc bất kỳ hoạt động mua lại, thanh lý hay tài trợ nào của một tổ chức hoặc một phần của một tổ chức hoặc của bất kỳ hoạt động kinh doanh hay tài sản nào của một tổ chức; và/hoặc
                            Bất kỳ mục đích nào mà chúng tôi thông báo cho bạn tại thời điểm xin sự cho phép của bạn
                            (gọi chung là “Các Mục Đích”)
                            5.2         Người Sử Dụng công nhận, cho phép và đồng ý rằng Foody có thể truy cập, duy trì và tiết lộ thông tin Tài Khoản của Người Sử Dụng và Nội dung trong trường hợp pháp luật có yêu cầu hoặc theo lệnh của tòa án hoặc cơ quan chính phủ hoặc cơ quan nhà nước có thẩm quyền yêu cầu Foody hoặc trong trường hợp việc duy trì hay tiết lộ thông tin này là thực sự cần thiết: (a) tuân theo các thủ tục pháp lý; (b) tuân theo yêu cầu của cơ quan chính phủ hoặc cơ quan nhà nước có thẩm quyền yêu cầu Foody; (c) thực thi Điều Khoản Dịch Vụ hoặc Chính sách bảo mật của Foody; (d) phản hồi các khiếu nại thực tế hoặc mang tính chất đe dọa đưa ra chống lại Foody hoặc những khiếu nại mà nội dung của chúng xâm phạm đến quyền lợi của bên thứ ba; (e) phản hồi các yêu cầu của Người Sử Dụng liên quan đến chăm sóc khách hàng; hoặc (f) bảo vệ các quyền, tài sản hoặc sự an toàn của Foody, Người Sử Dụng và/hoặc cộng đồng.
                            5.3         Vì Các Mục Đích mà chúng tôi sẽ/có thể thu thập, sử dụng, tiết lộ hoặc xử lý dữ liệu cá nhân của bạn tùy thuộc vào hoàn cảnh thực tế, mục đích đó có thể chưa được đề cập ở trên. Tuy nhiên, chúng tôi sẽ thông báo cho bạn biết mục đích khác đó tại thời điểm xin sự cho phép của bạn, trừ phi việc xử lý dữ liệu áp dụng mà không có sự đồng ý của bạn là được phép theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân hoặc theo quy định pháp luật về quyền riêng tư.{'\n'}</Text>

                        <Text style={{ fontSize: 15, color: '#000' }}>Điều 6: Foody bảo vệ và lưu trữ thông tin khách hàng bằng cách nào?{'\n'}</Text>
                        <Text>
                            6.1         Chúng tôi thực hiện các biện pháp bảo mật khác nhau và luôn nỗ lực để đảm bảo sự an toàn cho dữ liệu cá nhân của bạn trên các hệ thống của chúng tôi. Dữ liệu cá nhân của người dùng được lưu trữ đằng sau các mạng bảo mật và chỉ có thể được truy cập bởi một số nhân viên có quyền truy cập đặc biệt đến các hệ thống của chúng tôi. Tuy nhiên không thể đảm bảo sự bảo mật tuyệt đối
                            6.2         Chúng tôi sẽ duy trì dữ liệu cá nhân tuân theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân và/hoặc các điều luật hiện hành khác. Có nghĩa là, chúng tôi sẽ hủy hoặc xóa thông tin cá nhân của bạn khi chúng tôi có lý do hợp lý để xác định rằng (i) việc lưu giữ dữ liệu cá nhân đó không còn phục vụ mục đích thu thập dữ liệu cá nhân đó nữa; (ii) việc lưu giữ không còn cần thiết cho bất kỳ mục đích hợp pháp hay mục đích kinh doanh nào và (iii) không còn các lợi ích hợp pháp nào khác để tiếp tục lưu giữ các dữ liệu cá nhân này. Nếu bạn ngưng sử dụng Nền tảng của chúng tôi, hoặc quyền của bạn được sử dụng Nền tảng và/hoặc Các Dịch Vụ bị chấm dứt hoặc bị thu hồi, chúng tôi có thể tiếp tục lưu, sử dụng và/hoặc tiết lộ dữ liệu cá nhân của bạn tuân theo Chính sách bảo mật này và các nghĩa vụ của chúng tôi theo các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân. Tùy thuộc vào quy định của pháp luật, chúng tôi có thể tiêu hủy dữ liệu cá nhân của bạn một cách an toàn mà không cần thông báo trước cho bạn.{'\n'}</Text>

                        <Text style={{ fontSize: 15, color: '#000' }}> Điều 7: Foody có tiết lộ thông tin thu thập từ người truy cập cho bên khác hay không?{'\n'}</Text>

                        <Text>
                            7.1         Trong quá trình vận hành hoạt động kinh doanh, chúng tôi sẽ/có thể cần phải tiết lộ dữ liệu cá nhân của bạn cho các nhà cung cấp dịch vụ bên thứ ba, đại lý và/hoặc các công ty liên kết hoặc công ty liên quan của chúng tôi, và/hoặc các bên thứ ba khác, vì một hay nhiều Mục Đích nói trên, và việc tiết lộ này sẽ được thực hiện theo đúng trình tự và quy định của pháp luật hiện hành. Các nhà cung cấp dịch vụ bên thứ ba, đại lý và/hoặc các công ty liên kết hoặc công ty liên quan và/hoặc các bên thứ ba khác sẽ xử lý dữ liệu cá nhân của bạn hoặc thay mặt chúng tôi hoặc khác, vì một hoặc nhiều Mục Đích nói trên. Các bên thứ ba như thế bao gồm, không giới hạn:
                            Công ty con, công ty liên kết và công ty liên quan của chúng tôi;
                            Người bán hoặc người mua mà bạn có giao dịch hoặc tương tác trên Nền tảng hoặc có liên quan đến việc sử dụng Các Dịch Vụ của bạn cho các mục đích nói trên;
                            Các người dùng khác trên Nền tảng của chúng tôi với một hoặc hơn một các mục đích nói trên;
                            Nhà thầu, đại lý, nhà cung cấp dịch vụ và các bên thứ ba khác mà chúng tôi thuê để hỗ trợ cho hoạt động kinh doanh của mình. Những bên này bao gồm, nhưng không giới hạn ở những bên cung cấp các dịch vụ quản trị hoặc các dịch vụ khác cho chúng tôi chẳng hạn như công ty bưu chính, nhà cung cấp dịch vụ vận chuyển, nhà cung cấp dịch vụ tài chính, đối tác quảng cáo và tiếp thị, công ty viễn thông, công ty công nghệ thông tin và trung tâm dữ liệu;
                            Các cơ quan chính phủ, cơ quan nhà nước có thẩm quyền đối với Foody hoặc các bên khác được cấp phép như Điều 6.2
                            Người mua hoặc người kế nhiệm khác trong trường hợp sáp nhập, thoái vốn, tái cơ cấu, tái tổ chức, giải thể hoặc bán hay chuyển nhượng một phần hoặc tất cả tài sản của Foody, cho dù là vấn đề đang diễn ra hay đang trong thủ tục phá sản, thanh lý hoặc thủ tục tương tự, trong đó dữ liệu cá nhân Foody lưu giữ về người dùng của chúng tôi nằm trong các tài sản được chuyển nhượng; hoặc cho một bên đối tác trong một giao dịch tài sản kinh doanh mà Foody hoặc bất kỳ công ty liên kết hay công ty liên quan nào của nó có tham gia giao dịch; và
                            Bên thứ ba mà chúng tôi tiết lộ thông tin vì một trong các Mục Đích và các bên thứ ba đó ngược lại họ sẽ thu thập và xử lý dữ liệu cá nhân của bạn vì một hoặc nhiều Mục Đích
                            7.2         Chúng tôi có thể chia sẻ thông tin người dùng, bao gồm thông tin thống kê và nhân khẩu học, về người dùng và thông tin về việc sử dụng Các Dịch Vụ của họ với các đối tác quảng cáo và nhà cung cấp quảng cáo bên thứ ba, để tiếp thị lại, và/ hoặc cho các chương trình khác.
                            7.3         Để tránh nghi ngờ, trong trường hợp các quy định của pháp luật về bảo vệ bí mật thông tin cá nhân hoặc các điều luật hiện hành khác cho phép một tổ chức chẳng hạn như chúng tôi thu thập, sử dụng hoặc tiết lộ dữ liệu cá nhân của bạn mà không cần sự đồng ý của bạn, sự cho phép như thế của pháp luật sẽ tiếp tục áp dụng. Phù hợp với các quy định nêu trên và quy định của pháp luật, chúng tôi có thể sử dụng thông tin cá nhân của bạn để xác định các cơ sở pháp lý bao gồm tuân thủ các nghĩa vụ pháp lý của chúng tôi, để thực hiện hợp đồng với bạn, để đạt được các lợi ích hợp pháp và lý do để chúng tôi sử dụng thông tin của bạn lớn hơn bất kỳ phương hại nào đến quyền bảo vệ dữ liệu của bạn hoặc khi cần thiết liên quan đến khiếu nại pháp lý.
                            7.4         Các bên thứ ba có thể chặn hoặc truy cập trái phép dữ liệu cá nhân được gửi đến hoặc có trên trang web, các công nghệ có thể hoạt động không chính xác hoặc không hoạt động như dự kiến, hoặc có người có thể truy cập, lạm dụng hoặc sử dụng sai trái thông tin mà không phải lỗi của chúng tôi. Tuy nhiên chúng tôi sẽ triển khai các biện pháp bảo mật phù hợp để bảo vệ dữ liệu cá nhân của bạn theo quy định của pháp luật về bảo vệ bí mật thông tin cá nhân; tuy nhiên không thể đảm bảo sự bảo mật tuyệt đối chẳng hạn như trường hợp tiết lộ trái phép phát sinh từ hoạt động tin tặc vì ý đồ xấu hoặc phức tạp của các nội dung có độc không phải lỗi của chúng tôi.
                            7.5         Như được quy định trong Điều khoản Dịch vụ của Foody, người dùng sở hữu dữ liệu cá nhân của Người dùng khác thông qua việc sử dụng Dịch vụ (“Bên nhận”) theo đây đồng ý rằng, họ sẽ (i) tuân thủ tất cả các luật bảo vệ dữ liệu cá nhân hiện hành liên quan đến bất kỳ dữ liệu nào như vậy; (ii) cho phép Người dùng có dữ liệu cá nhân mà Bên nhận đã thu thập (“Bên tiết lộ”) xóa dữ liệu của họ đã thu thập khỏi cơ sở dữ liệu của Bên nhận; và (iii) cho phép Bên tiết lộ xem xét thông tin nào đã được Bên nhận thu thập về họ, trong từng trường hợp (ii) và (iii) ở trên, tuân thủ và khi được yêu cầu bởi luật hiện hành.
                            7.6         Ngoài những điều được nêu ở trên, Người dùng khi nhận được bất kỳ dữ liệu cá nhân nào của Người dùng khác liên quan đến việc sử dụng Dịch vụ phải tuân thủ tất cả các Luật về quyền riêng tư hiện hành và đối với bất kỳ dữ liệu cá nhân nào của Bên tiết lộ như vậy nhận được từ Foody, (i) không được phép sử dụng dữ liệu cá nhân đó trừ khi cần thiết một cách hợp lý nhằm thực hiện phản hồi, xử lý, giải quyết hoặc hoàn thành một giao dịch, ngoại trừ sự đồng ý trước bằng văn bản của Bên tiết lộ đó và Foody; (ii) không được liên hệ với Người dùng sử dụng thông tin đó bên ngoài nền tảng Foody; (iii) không được phép tiết lộ dữ liệu cá nhân của Bên tiết lộ đó cho bất kỳ bên thứ ba trái phép nào mà không có sự đồng ý trước bằng văn bản của Bên tiết lộ và Foody; (iv) cần sử dụng các biện pháp bảo mật đầy đủ để bảo vệ dữ liệu cá nhân của mỗi Người dùng Foody mà họ sở hữu và xóa dữ liệu đó càng sớm càng tốt sau khi hoàn thành giao dịch; và (v) cần thông báo cho Nhân viên Bảo vệ Dữ liệu Cá nhân của Foody tại ĐÂY trong trường hợp có khả năng vi phạm dữ liệu hoặc mất mát dữ liệu của Người dùng đó.{'\n'}</Text>

                        <Text style={{ fontSize: 15, color: '#000' }}>  Điều 8: Thông tin thu thập bởi các bên thứ ba{'\n'}</Text>
                        <Text>
                            8.1         Nền tảng của chúng tôi sử dụng Google Analytics, một dịch vụ phân tích web được cung cấp bởi Google, Inc. ("Google"). Google Analytics sử dụng cookie, là các tập tin văn bản được đặt vào thiết bị của bạn, để giúp Nền tảng phân tích cách thức người dùng sử dụng Nền tảng của chúng tôi. Thông tin được tạo bởi cookie về việc bạn sử dụng Nền tảng (bao gồm địa chỉ IP của bạn) sẽ được gửi đến và lưu bởi Google trên các máy chủ tại Hoa Kỳ. Google sẽ sử dụng thông tin này để đánh giá việc bạn sử dụng Nền tảng của chúng tôi, soạn báo cáo về hoạt động trang web dành cho các nhà điều hành trang web và cung cấp các dịch vụ khác liên quan đến hoạt động trang web và việc sử dụng Internet. Google cũng có thể gửi thông tin này cho các bên thứ ba trong trường hợp luật pháp có quy định như thế, hoặc trường hợp các bên thứ ba đó xử lý thông tin thay mặt Google. Google sẽ không liên kết địa chỉ IP của bạn với bất kỳ dữ liệu nào khác mà Google nắm giữ.
                            8.2         Chúng tôi, và các bên thứ ba, trong một vài trường hợp có thể cung cấp các bản tải về ứng dụng phần mềm cho bạn sử dụng bởi Nền tảng hoặc thông qua Các Dịch Vụ. Những ứng dụng này có thể truy cập riêng, và cho phép một bên thứ ba xem, thông tin nhận dạng của bạn, chẳng hạn như tên, ID người dùng của bạn, Địa chỉ IP của thiết bị của bạn hoặc thông tin khác chẳng hạn như game bạn đang chơi trong bất kỳ phiên truy cập cụ thể nào, và bất kỳ cookie nào trước đây bạn có thể đã cài đặt hoặc đã được cài đặt cho bạn bởi một ứng dụng phần mềm hoặc trang web của bên thứ ba. Ngoài ra, các ứng dụng này có thể yêu cầu bạn cung cấp thêm thông tin trực tiếp cho các bên thứ ba. Các sản phẩm hoặc dịch vụ của bên thứ ba được cung cấp thông qua các ứng dụng này không thuộc sở hữu hay quyền kiểm soát của Foody. Bạn nên đọc các điều khoản và các chính sách khác được công bố bởi các bên thứ ba đó trên trang web của họ hoặc nơi khác.{'\n'}</Text>
                        <Text style={{ fontSize: 15, color: '#000' }}>Điều 9: Loại trừ trách nhiệm về nghĩa vụ bảo mật và các trang web bên thứ ba{'\n'}</Text>
                        <Text>
                            9.1         CHÚNG TÔI KHÔNG ĐẢM BẢO TÍNH BẢO MẬT ĐỐI VỚI DỮ LIỆU CÁ NHÂN VÀ/HOẶC THÔNG TIN KHÁC MÀ BẠN CUNG CẤP TRÊN CÁC TRANG WEB CỦA BÊN THỨ BA. Chúng tôi thực hiện các biện pháp bảo mật khác nhau để duy trì sự an toàn của dữ liệu cá nhân của bạn mà chúng tôi lưu giữ hoặc kiểm soát. Dữ liệu cá nhân của bạn được lưu đằng sau các mạng bảo mật và chỉ có thể được truy cập bởi một số cá nhân giới hạn có quyền truy cập đặc biệt đến các hệ thống của chúng tôi, và đã được yêu cầu bảo mật dữ liệu cá nhân đó. Khi bạn đặt hàng hoặc truy cập dữ liệu cá nhân của bạn, chúng tôi đề nghị sử dụng một máy chủ bảo mật. Tất cả dữ liệu cá nhân hoặc thông tin cá nhân bạn cung cấp sẽ được mã hóa vào các cơ sở dữ liệu của chúng tôi để chỉ được truy cập như mô tả bên trên.
                            9.2         Nhằm cung cấp cho bạn giá trị gia tăng, chúng tôi có thể chọn các trang web hoặc ứng dụng hoặc dịch vụ của bên thứ ba khác nhau để liên kết, và đóng khung bên trong Nền tảng. Chúng tôi cũng có thể tham gia các quan hệ cùng tiếp thị và các quan hệ khác để cung cấp dịch vụ thương mại điện tử và các dịch vụ và tính năng khác cho khách truy cập. Những trang được liên kết này có các chính sách về quyền riêng tư cũng như các biện pháp bảo mật riêng và độc lập. Ngay cả khi bên thứ ba đó có liên kết với chúng tôi, chúng tôi cũng không kiểm soát các trang web/ứng dụng/dịch vụ được liên kết này, mỗi trang đó có các phương pháp bảo vệ quyền riêng tư và thu thập dữ liệu riêng biệt, độc lập với chúng tôi. Dữ liệu thu thập bởi các đối tác cùng tiếp thị của chúng tôi hoặc các trang web/ứng dụng/dịch vụ của bên thứ ba (ngay cả khi được cung cấp trên hoặc thông qua Nền tảng của chúng tôi) có thể không được chúng tôi tiếp cận và/hoặc lưu giữ.
                            9.3         Do đó chúng tôi không chịu trách nhiệm hay trách nhiệm pháp lý đối với nội dung, các biện pháp bảo mật (hoặc sự thiếu biện pháp bảo mật) và các hoạt động của các trang web/ứng dụng/dịch vụ được liên kết này. Những trang web/ứng dụng/dịch vụ được liên kết này chỉ vì sự thuận tiện cho bạn và do đó bạn tự chịu trách nhiệm khi truy cập chúng. Tuy nhiên, chúng tôi tìm cách bảo vệ tính toàn vẹn của Nền tảng của chúng tôi và các liên kết được đặt trên từng trang web đó và do đó chúng tôi hoan nghênh ý kiến phản hồi về các trang web được liên kết này (bao gồm nếu một trang web cụ thể không hoạt động).{'\n'}</Text>
                        <Text style={{ fontSize: 15, color: '#000' }}>Điều 10: OderFood có chuyển thông tin của bạn ra nước ngoài không?{'\n'}</Text>
                        <Text>
                            10.1         Dữ liệu cá nhân của bạn và/hoặc các thông tin khác có thể được chuyển, lưu trữ hay xử lý ở ngoài địa phận quốc gia của bạn. Trong đa số trường hợp, dữ liệu cá nhân của bạn sẽ được xử lý ở Việt Nam, nơi chúng tôi đặt máy chủ. Foody chỉ chuyển thông tin của bạn ra nước ngoài theo đúng quy định của pháp luật.{'\n'}</Text>
                        <Text style={{ fontSize: 15, color: '#000' }}>Điều 11: Bạn có thể rút lại sự đồng ý, yêu cầu truy cập hoặc điều chỉnh thông tin bạn đã cung cấp cho chúng tôi bằng cách nào?{'\n'}</Text>
                        <Text>
                            11.1.        Rút Lại Sự Đồng Ý
                            11.1.1        Bạn có thể rút lại sự đồng ý cho phép thu thập, sử dụng và/hoặc tiết lộ dữ liệu cá nhân của bạn mà chúng tôi đang lưu giữ hoặc kiểm soát bằng cách gửi email cho Bộ phận Bảo Vệ Dữ Liệu Cá Nhân của chúng tôi tại địa chỉ email dpo.vn@foody.com và chúng tôi sẽ xử lý các yêu cầu này theo Chính Sách Bảo Mật cũng như quy định pháp luật có liên quan
                            11.1.2.        Chúng tôi có thể định kỳ gửi cho bạn các bản tin và e-mail quảng bá trực tiếp Dịch vụ của chúng tôi nếu bạn đăng ký nhận những thông tin liên lạc này. Bạn có cơ hội “chọn không tham gia” (ví dụ: bằng cách làm theo hướng dẫn hủy đăng ký được cung cấp trong e-mail bạn nhận được). Chúng tôi cần gửi cho bạn một số thông tin liên lạc nhất định liên quan đến chúng tôi hoặc các dịch vụ của chúng tôi và bạn sẽ không thể chọn không nhận các thông tin liên lạc đó (chẳng hạn như thông tin liên quan đến cập nhật Điều khoản dịch vụ của chúng tôi, Chính sách bảo mật này, thông tin về lập hóa đơn hoặc thanh toán hoặc dịch vụ khách hàng).
                            11.2.        Thông báo bổ sung cho Người dùng mà dữ liệu cá nhân thuộc phạm vị điều chỉnh của Luật California
                            {'\n'}</Text>
                    </Text>
                </View>
            </ScrollView>

        </View>
    )
}

export default ScreenPolicyAndPrivacy